name: .NET

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    env:
      ProjectName: Toca3DifficultyEditor
      TargetPlatform: win-x64

    runs-on: windows-latest

    steps:
    - name: Clone
      uses: actions/checkout@v4

    - name: Initialize test reporting
      uses: testspace-com/setup-testspace@v1
      with:
        domain: ${{github.repository_owner}}
        
    - name: Restore
      run: dotnet restore --locked-mode --verbosity normal

    - name: Build
      run: dotnet build ${{ env.ProjectName }} --no-restore --runtime ${{ env.TargetPlatform }} --configuration Release --no-self-contained

    - name: Publish
      run: dotnet publish ${{ env.ProjectName }} --no-build --configuration Release -p:PublishSingleFile=true --runtime ${{ env.TargetPlatform }} --self-contained false

    - name: Test
      run: |
        dotnet test --verbosity normal --configuration Release --collect:"XPlat Code Coverage" --settings Tests/Tests.runsettings --logger "trx;LogFileName=TestResults.xml"
        Out-File -InputObject "TEST_EXIT_CODE=$LASTEXITCODE" -FilePath $env:GITHUB_ENV -Append -Encoding UTF8
        Copy-Item Tests/TestResults/*/coverage.info Tests/TestResults -ErrorAction Continue
        exit 0

    - name: Upload test report
      run: testspace Tests/TestResults/TestResults.xml

    - name: Upload coverage
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        files: Tests/TestResults/coverage.info
        format: lcov

    - name: Stop if tests failed
      run: exit $env:TEST_EXIT_CODE

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ProjectName }}.exe
        path: ${{ env.ProjectName }}/bin/Release/net8.0-windows/${{ env.TargetPlatform }}/publish/*.exe
        if-no-files-found: error
